name: "Pull Request Labeler"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml

A-Action:
  - '**/*.yml'

A-documentation:
  - '**/*.md'
  - 'internal/lints/README.md'
  - '!docs/rfc/**/*'

A-lint:
  - 'internal/lints/**/*'

T-engine:
  - 'internal/engine/**/*'

T-fixer:
  - 'internal/fixer/**/*'

T-format:
  - 'formatter/**/*'

T-CLI:
  - 'cmd/**/*'

L-test:
  - '**/*_test.go'
  - 'testdata/**/*'

RFC:
  - 'docs/rfc/**/*'
