linters-settings:
  typecheck:
    # Keep the linter enabled (since it can't be disabled), but exclude all its messages
    disable: false

exclude-rules:
  - linters:
      - typecheck
      - gosimple
    text: '.*'
