# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  lint:
    name: Go linter
    uses: ./.github/workflows/lint.yml

  test:
    name: Go test
    uses: ./.github/workflows/test.yml
